version: 2
updates:
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci: "
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci: "
  - package-ecosystem: pip
    versioning-strategy: increase-if-necessary
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "feat(deps): "
      prefix-development: "chore(deps-dev): "
